import { Product, Category, Review, Currency, Coupon, Customer } from '../types';
import heroTechImg from '../assets/images/umarmart_hero_tech_1785587505993.jpg';
import heroFashionImg from '../assets/images/umarmart_hero_fashion_1785587522235.jpg';

export const HERO_SLIDES = [
  {
    id: 'slide-1',
    title: 'Experience Pure Acoustic Precision',
    subtitle: 'UmarMart Exclusive Audio Series',
    heading: 'Next-Gen ANC Wireless Headphones',
    description: 'Immerse yourself in studio-grade sound with active noise cancellation, 60-hour battery life, and spatial audio technology.',
    image: heroTechImg,
    badge: 'NEW RELEASE',
    price: 'Rs. 2,499',
    originalPrice: 'Rs. 3,499',
    ctaText: 'Shop Tech Now',
    categorySlug: 'mobiles'
  },
  {
    id: 'slide-2',
    title: 'Precision Craftsmanship & Style',
    subtitle: 'UmarMart Luxury Collection',
    heading: 'Automatic Chronograph Royal Edition',
    description: 'Forged from aerospace-grade titanium with sapphire crystal glass and Japanese automatic movement. Waterproof up to 100m.',
    image: heroFashionImg,
    badge: 'LIMITED EDITION',
    price: 'Rs. 12,999',
    originalPrice: 'Rs. 16,500',
    ctaText: 'Explore Watches',
    categorySlug: 'fashion'
  },
  {
    id: 'slide-3',
    title: 'Supercharge Your Smart Living',
    subtitle: 'Flash Deal Event',
    heading: 'Ultra-Slim OLED 4K Smart Monitor',
    description: 'Quantum Dot display technology with 240Hz refresh rate and built-in AI visual processing for gaming and productivity.',
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80',
    badge: 'FLASH SALE • 30% OFF',
    price: 'Rs. 49,999',
    originalPrice: 'Rs. 69,999',
    ctaText: 'Grab The Deal',
    categorySlug: 'laptops'
  }
];

export const CATEGORIES: Category[] = [
  {
    id: 'cat-mobiles',
    name: 'Mobiles',
    slug: 'mobiles',
    iconName: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80',
    itemCount: 12,
    description: 'Latest 5G smartphones, iPhones, flagship Android devices & accessories.'
  },
  {
    id: 'cat-laptops',
    name: 'Laptops',
    slug: 'laptops',
    iconName: 'Laptop',
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80',
    itemCount: 8,
    description: 'High-performance laptops, MacBooks, gaming rigs & ultrabooks.'
  },
  {
    id: 'cat-fashion',
    name: 'Fashion',
    slug: 'fashion',
    iconName: 'Shirt',
    image: 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=600&q=80',
    itemCount: 10,
    description: 'Designer menswear, eastern unstitched lawns, luxury shoes & watches.'
  },
  {
    id: 'cat-beauty',
    name: 'Beauty',
    slug: 'beauty',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80',
    itemCount: 6,
    description: 'Skincare essentials, luxury perfumes, cosmetics & hair styling tools.'
  },
  {
    id: 'cat-grocery',
    name: 'Grocery',
    slug: 'grocery',
    iconName: 'ShoppingBag',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    itemCount: 6,
    description: 'Fresh organic staples, premium tea, olive oil & imported pantry essentials.'
  },
  {
    id: 'cat-home',
    name: 'Home Appliances',
    slug: 'home-appliances',
    iconName: 'Home',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=600&q=80',
    itemCount: 8,
    description: 'Air fryers, espresso machines, robot vacuums & smart appliances.'
  },
  {
    id: 'cat-sports',
    name: 'Sports',
    slug: 'sports',
    iconName: 'Dumbbell',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
    itemCount: 6,
    description: 'Fitness gear, cricket equipment, running shoes & training accessories.'
  },
  {
    id: 'cat-books',
    name: 'Books',
    slug: 'books',
    iconName: 'BookOpen',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    itemCount: 6,
    description: 'Bestselling non-fiction, self-help classics, literature & Islamic books.'
  }
];

export const PRODUCTS: Product[] = [
  // --- MOBILES (12) ---
  {
    id: 'prod-mob-1',
    name: 'Apple iPhone 15 Pro Max 256GB Titanium Blue (PTA Approved)',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 485000,
    originalPrice: 519000,
    rating: 4.9,
    reviewsCount: 382,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    isBestSeller: true,
    stock: 12,
    salesCount: 420,
    badge: 'PTA APPROVED',
    description: 'Forged in titanium with revolutionary A17 Pro chip, customizable Action button, and the most powerful iPhone camera system ever with 5x Telephoto optical zoom.',
    features: ['Aerospace-Grade Titanium Design', 'A17 Pro Chip with 6-Core GPU', '48MP Main Camera + 5x Optical Zoom', 'Super Retina XDR Display with ProMotion'],
    specs: [{ label: 'Storage', value: '256 GB' }, { label: 'RAM', value: '8 GB' }, { label: 'Warranty', value: '1 Year Apple Official' }]
  },
  {
    id: 'prod-mob-2',
    name: 'Samsung Galaxy S24 Ultra 512GB Titanium Gray (PTA Approved)',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 399999,
    originalPrice: 435000,
    rating: 4.9,
    reviewsCount: 290,
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    isFlashSale: true,
    flashSaleEnd: '2026-08-05T23:59:59',
    stock: 8,
    salesCount: 310,
    badge: 'FLASH SALE',
    description: 'Welcome to the era of mobile AI. Galaxy AI powers photo editing, instant live call translation, and Circle to Search, built with built-in S Pen.',
    features: ['Galaxy AI Live Translation & Circle to Search', '200MP Quad Telephoto Camera System', 'Snapdragon 8 Gen 3 for Galaxy', 'Built-in S Pen Stylus'],
    specs: [{ label: 'Display', value: '6.8" Dynamic AMOLED 2X 120Hz' }, { label: 'Battery', value: '5000 mAh' }]
  },
  {
    id: 'prod-mob-3',
    name: 'Xiaomi 14 Ultra 5G Leica Quad Camera (PTA Approved)',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 299999,
    originalPrice: 329000,
    rating: 4.8,
    reviewsCount: 145,
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
    isTrending: true,
    stock: 15,
    salesCount: 180,
    description: 'Co-engineered with Leica, featuring a 1-inch LYT-900 sensor with stepless variable aperture and 90W HyperCharge.',
    features: ['Leica Quad Camera System', '1-inch Sony LYT-900 Sensor', 'Snapdragon 8 Gen 3', '90W Fast Charging'],
    specs: [{ label: 'RAM', value: '16 GB' }, { label: 'Storage', value: '512 GB' }]
  },
  {
    id: 'prod-mob-4',
    name: 'OnePlus 12 5G Silky Black 16GB / 512GB',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 245000,
    originalPrice: 265000,
    rating: 4.7,
    reviewsCount: 198,
    image: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
    stock: 14,
    salesCount: 260,
    description: 'Powered by Snapdragon 8 Gen 3 with 4th Gen Hasselblad Camera for Mobile and 100W SUPERVOOC charging.',
    features: ['Hasselblad Camera for Mobile', '100W SUPERVOOC Fast Charging', '2K 120Hz ProXDR Display'],
    specs: [{ label: 'Battery', value: '5400 mAh' }, { label: 'RAM', value: '16 GB' }]
  },
  {
    id: 'prod-mob-5',
    name: 'Google Pixel 8 Pro 256GB Obsidian Black',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 269999,
    originalPrice: 289999,
    rating: 4.8,
    reviewsCount: 164,
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
    stock: 10,
    salesCount: 195,
    description: 'Designed by Google with custom Tensor G3 chip, advanced AI video boost, Best Take feature, and 7 years of OS updates.',
    features: ['Google Tensor G3 Processor', 'AI Best Take & Audio Magic Eraser', '7 Years of Android Updates'],
    specs: [{ label: 'Screen', value: '6.7" Super Actua Display' }]
  },
  {
    id: 'prod-mob-6',
    name: 'Vivo V30 Pro 5G ZEISS Portrait Camera 512GB',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 159999,
    originalPrice: 175000,
    rating: 4.7,
    reviewsCount: 215,
    image: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
    stock: 20,
    salesCount: 410,
    description: 'Professional portrait smartphone equipped with ZEISS Professional Optics, Aura Light Portrait, and 80W FlashCharge.',
    features: ['ZEISS Professional Portrait Camera', 'Smart Aura Light System', '5000mAh Ultra-Slim Battery'],
    specs: [{ label: 'RAM', value: '12 GB + 12 GB Extended' }]
  },
  {
    id: 'prod-mob-7',
    name: 'Realme GT 5 Pro 512GB Snapdragon 8 Gen 3',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 179999,
    originalPrice: 199999,
    rating: 4.6,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?auto=format&fit=crop&w=800&q=80',
    stock: 18,
    salesCount: 220,
    description: 'Flagship killer performance featuring Sony LYT-808 sensor, 3X Periscope Telephoto lens, and 100W fast charge.',
    features: ['Sony LYT-808 Camera Sensor', '3X Optical Periscope Lens', '4500 nits Peak Brightness'],
    specs: [{ label: 'Charging', value: '100W Wired + 50W Wireless' }]
  },
  {
    id: 'prod-mob-8',
    name: 'Infinix Zero 30 5G 256GB Golden Hour 4K 60FPS Vlog',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 84999,
    originalPrice: 94999,
    rating: 4.5,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1546054454-aa26e2b734c7?auto=format&fit=crop&w=800&q=80',
    stock: 35,
    salesCount: 890,
    description: 'World’s first 50MP 4K 60fps Front Vlog Camera phone with 144Hz 3D Curved AMOLED display.',
    features: ['50MP 4K 60FPS Front Vlog Camera', '144Hz 3D Curved AMOLED Display', '68W Super Charge'],
    specs: [{ label: 'Front Camera', value: '50 MP Eye AF' }]
  },
  {
    id: 'prod-mob-9',
    name: 'UmarMart SoundMax Wireless ANC Headphones Pro',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 2499,
    originalPrice: 3499,
    rating: 4.9,
    reviewsCount: 328,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
    isFlashSale: true,
    stock: 14,
    salesCount: 1420,
    badge: '30% OFF',
    description: 'Top-of-the-line wireless ANC headphones with custom 40mm titanium drivers and 60-hour battery life.',
    features: ['Active Noise Cancellation', '60-Hour Playback', 'Bluetooth 5.3 Multipoint'],
    specs: [{ label: 'Driver', value: '40mm Titanium' }]
  },
  {
    id: 'prod-mob-10',
    name: 'PulseX Pro True Wireless Noise-Canceling Earbuds',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 3999,
    originalPrice: 5499,
    rating: 4.8,
    reviewsCount: 395,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
    stock: 30,
    salesCount: 1620,
    description: 'Compact wireless earbuds delivering deep bass, IPX7 waterproof rating, and 32h total playtime.',
    features: ['38dB Noise Cancellation', 'Wireless QI Charging', '6-Mic HD Calls'],
    specs: [{ label: 'Playtime', value: '32 Hours Total' }]
  },
  {
    id: 'prod-mob-11',
    name: 'Anker PowerCore 24000mAh 65W Fast Power Bank',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 11999,
    originalPrice: 14999,
    rating: 4.9,
    reviewsCount: 175,
    image: 'https://images.unsplash.com/photo-1609592424074-954955b23d91?auto=format&fit=crop&w=800&q=80',
    stock: 22,
    salesCount: 540,
    description: 'Heavy duty 65W USB-C PD fast power bank capable of charging laptops, iPhones and Android smartphones simultaneously.',
    features: ['65W USB-C Power Delivery', '24,000mAh Massive Capacity', 'Digital OLED Power Display'],
    specs: [{ label: 'Ports', value: '2x USB-C, 1x USB-A' }]
  },
  {
    id: 'prod-mob-12',
    name: 'MagSafe Wireless Fast Car Charger Mount',
    category: 'Mobiles',
    categorySlug: 'mobiles',
    price: 3499,
    originalPrice: 4999,
    rating: 4.7,
    reviewsCount: 240,
    image: 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?auto=format&fit=crop&w=800&q=80',
    stock: 40,
    salesCount: 780,
    description: 'Strong magnetic air vent car phone holder with 15W wireless fast charging for iPhone and Android devices.',
    features: ['N52 Ultra-Strong Neodymium Magnets', '15W Qi Fast Charging', '360-degree Rotation'],
    specs: [{ label: 'Mounting', value: 'Air Vent Clamp' }]
  },

  // --- LAPTOPS (8) ---
  {
    id: 'prod-lap-1',
    name: 'Apple MacBook Pro 16" M3 Max 36GB / 1TB Liquid Retina XDR',
    category: 'Laptops',
    categorySlug: 'laptops',
    price: 899999,
    originalPrice: 949000,
    rating: 5.0,
    reviewsCount: 128,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    isBestSeller: true,
    stock: 6,
    salesCount: 95,
    badge: 'M3 MAX POWER',
    description: 'The ultimate pro laptop featuring 16-core CPU, 40-core GPU, Liquid Retina XDR display with 1600 nits peak brightness and 22 hours battery life.',
    features: ['Apple M3 Max Chip with 40-Core GPU', '36GB Unified Memory + 1TB SSD', '16.2" Liquid Retina XDR 120Hz Display', 'Up to 22 Hours Battery Life'],
    specs: [{ label: 'Processor', value: 'M3 Max 16-Core' }, { label: 'Display', value: '16.2" XDR 3456x2234' }]
  },
  {
    id: 'prod-lap-2',
    name: 'Dell XPS 15 OLED Touch 13th Gen i9 32GB RTX 4070 1TB',
    category: 'Laptops',
    categorySlug: 'laptops',
    price: 649999,
    originalPrice: 699999,
    rating: 4.8,
    reviewsCount: 94,
    image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    stock: 5,
    salesCount: 110,
    description: 'Stunning 3.5K OLED touchscreen ultrabook crafted from CNC machined aluminum with NVIDIA GeForce RTX 4070 graphic engine.',
    features: ['3.5K OLED Touchscreen', 'Intel Core i9-13900H Processor', 'NVIDIA GeForce RTX 4070 8GB'],
    specs: [{ label: 'RAM', value: '32 GB DDR5' }, { label: 'Storage', value: '1 TB NVMe SSD' }]
  },
  {
    id: 'prod-lap-3',
    name: 'Asus ROG Zephyrus G14 Gaming Laptop Ryzen 9 RTX 4080',
    category: 'Laptops',
    categorySlug: 'laptops',
    price: 529999,
    originalPrice: 579000,
    rating: 4.9,
    reviewsCount: 162,
    image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=800&q=80',
    isTrending: true,
    stock: 8,
    salesCount: 140,
    description: 'Ultra-portable 14-inch ROG Nebula HDR OLED display gaming laptop featuring AniMe Matrix lid customization.',
    features: ['ROG Nebula OLED 3K 120Hz Screen', 'AMD Ryzen 9 8945HS CPU', 'NVIDIA RTX 4080 12GB Graphics'],
    specs: [{ label: 'Weight', value: '1.5 kg Ultra-Light' }]
  },
  {
    id: 'prod-lap-4',
    name: 'HP Spectre x360 2-in-1 14" OLED Core Ultra 7 1TB SSD',
    category: 'Laptops',
    categorySlug: 'laptops',
    price: 389999,
    originalPrice: 419999,
    rating: 4.7,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1544731612-de7f96afe55f?auto=format&fit=crop&w=800&q=80',
    stock: 10,
    salesCount: 130,
    description: 'Versatile 360-degree convertible laptop with Intel Core Ultra 7 AI processor, 2.8K OLED screen, and rechargeable tilt pen.',
    features: ['2.8K OLED Touch Screen', 'Intel Core Ultra 7 NPU AI Engine', 'Includes HP Rechargeable Tilt Pen'],
    specs: [{ label: 'Battery', value: '68 Wh Fast Charge' }]
  },
  {
    id: 'prod-lap-5',
    name: 'Lenovo Legion Pro 5 Gen 9 i7 14th Gen RTX 4060 16GB',
    category: 'Laptops',
    categorySlug: 'laptops',
    price: 369999,
    originalPrice: 399999,
    rating: 4.8,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=800&q=80',
    stock: 12,
    salesCount: 200,
    description: 'AI-tuned Legion Coldfront 5.0 thermal cooling gaming laptop with 16" WQXGA 240Hz PureSight Gaming display.',
    features: ['16" WQXGA 240Hz 500 nits Display', 'Intel Core i7-14700HX', 'NVIDIA GeForce RTX 4060 8GB'],
    specs: [{ label: 'RAM', value: '16 GB DDR5 5600MHz' }]
  },
  {
    id: 'prod-lap-6',
    name: 'Acer Swift Go 14 OLED Intel Core Ultra 5 16GB / 512GB',
    category: 'Laptops',
    categorySlug: 'laptops',
    price: 199999,
    originalPrice: 225000,
    rating: 4.6,
    reviewsCount: 76,
    image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=800&q=80',
    stock: 15,
    salesCount: 165,
    description: 'Lightweight everyday productivity laptop with vibrant 90Hz OLED display, 1440p QHD webcam, and all-day battery.',
    features: ['14" 2.8K 90Hz OLED Panel', 'Intel Arc Graphics Built-in', 'Under 1.3kg Featherweight Chassis'],
    specs: [{ label: 'Screen', value: '2.8K OLED 100% DCI-P3' }]
  },
  {
    id: 'prod-lap-7',
    name: 'Ultra Slim OLED 4K Smart Display Monitor 27"',
    category: 'Laptops',
    categorySlug: 'laptops',
    price: 49999,
    originalPrice: 69999,
    rating: 4.8,
    reviewsCount: 210,
    image: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
    isFlashSale: true,
    stock: 5,
    salesCount: 450,
    badge: '30% OFF',
    description: '4K OLED monitor with 0.03ms response time, HDR True Black 400, USB-C 90W power delivery.',
    features: ['27-inch 4K OLED Quantum Panel', '240Hz Refresh Rate', 'USB-C 90W Charging'],
    specs: [{ label: 'Resolution', value: '3840 x 2160' }]
  },
  {
    id: 'prod-lap-8',
    name: 'CyberBlade RGB Mechanical Wireless Gaming Keyboard',
    category: 'Laptops',
    categorySlug: 'laptops',
    price: 5499,
    originalPrice: 7499,
    rating: 4.9,
    reviewsCount: 420,
    image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=800&q=80',
    stock: 9,
    salesCount: 1980,
    badge: 'TRENDING',
    description: 'Hot-swappable custom mechanical keyboard with gasket mount design and tri-mode wireless connection.',
    features: ['Gasket Mount Design', 'Tri-Mode Wireless', '8000mAh Battery'],
    specs: [{ label: 'Layout', value: '75% Compact' }]
  },

  // --- FASHION (10) ---
  {
    id: 'prod-fas-1',
    name: 'Executive Tailored Slim-Fit Italian Wool Suit',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 15999,
    originalPrice: 19999,
    rating: 4.9,
    reviewsCount: 96,
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    isBestSeller: true,
    stock: 12,
    salesCount: 620,
    description: 'Crafted from 100% fine Italian merino wool, this slim-fit 2-piece suit blends modern elegance with effortless comfort.',
    features: ['100% Italian Super 120s Wool', 'Modern Tailored Silhouette', 'Wrinkle-Resistant Natural Stretch'],
    specs: [{ label: 'Material', value: '100% Merino Wool' }],
    sizes: ['38R', '40R', '42R', '44R']
  },
  {
    id: 'prod-fas-2',
    name: 'Royal Chronograph Automatic Sapphire Watch',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 12999,
    originalPrice: 16500,
    rating: 5.0,
    reviewsCount: 184,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
    isBestSeller: true,
    stock: 8,
    salesCount: 890,
    badge: 'BEST SELLER',
    description: 'Automatic chronograph timepiece constructed from Grade 5 titanium and sapphire crystal glass.',
    features: ['Japanese Automatic Movement', '100m Water Resistance', 'Titanium Bezel'],
    specs: [{ label: 'Case', value: '42mm Titanium' }]
  },
  {
    id: 'prod-fas-3',
    name: 'Luxury Unstitched 3-Piece Lawn Embroidered Suit',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 6999,
    originalPrice: 8999,
    rating: 4.8,
    reviewsCount: 230,
    image: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=800&q=80',
    isTrending: true,
    stock: 25,
    salesCount: 940,
    badge: 'EASTERN LAWN',
    description: 'Premium Swiss lawn shirt with heavy schiffli embroidery, silk dupatta, and dyed trousers.',
    features: ['Heavy Schiffli Front Embroidery', '100% Pure Digital Printed Silk Dupatta', 'Swiss Cotton Lawn Fabric'],
    specs: [{ label: 'Pieces', value: '3 Piece Unstitched' }]
  },
  {
    id: 'prod-fas-4',
    name: 'Handcrafted Full-Grain Leather Oxford Formal Shoes',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 8499,
    originalPrice: 10999,
    rating: 4.9,
    reviewsCount: 154,
    image: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
    stock: 16,
    salesCount: 430,
    description: 'Classic Goodyear welted leather shoes handcrafted from full-grain calfskin with padded leather insoles.',
    features: ['Goodyear Welted Construction', 'Full-Grain Calfskin Leather', 'Cushioned Ortho-Sole'],
    specs: [{ label: 'Sole', value: 'Genuine Leather Outer' }]
  },
  {
    id: 'prod-fas-5',
    name: 'Luxe Cashmere Knit Sweater in Midnight Navy',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 7999,
    originalPrice: 9999,
    rating: 4.9,
    reviewsCount: 165,
    image: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
    stock: 15,
    salesCount: 510,
    badge: '100% CASHMERE',
    description: '100% Grade-A Mongolian cashmere knit sweater with relaxed modern neckline.',
    features: ['Grade-A Mongolian Cashmere', 'Breathable Natural Insulator', 'Ribbed Cuffs'],
    specs: [{ label: 'Origin', value: 'Mongolia' }],
    sizes: ['XS', 'S', 'M', 'L']
  },
  {
    id: 'prod-fas-6',
    name: 'Leather Executive Carry-On Travel Duffle Bag',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 9999,
    originalPrice: 12999,
    rating: 4.9,
    reviewsCount: 204,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80',
    stock: 11,
    salesCount: 730,
    description: 'Handcrafted full-grain Italian leather travel weekender with separate shoe compartment.',
    features: ['Full-Grain Italian Leather', 'Ventilated Shoe Pocket', 'Flight Carry-On Approved'],
    specs: [{ label: 'Dimensions', value: '21.5" x 11" x 10"' }]
  },
  {
    id: 'prod-fas-7',
    name: 'AeroGlide Smartwatch 2 Pro Ultra-Lightweight',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 8999,
    originalPrice: 11999,
    rating: 4.7,
    reviewsCount: 512,
    image: 'https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=800&q=80',
    stock: 22,
    salesCount: 1350,
    description: 'AMOLED smartwatch with heart rate monitor, GPS, and 14-day battery life.',
    features: ['1.43" AMOLED Display', 'Continuous SpO2 & ECG', '14-Day Battery'],
    specs: [{ label: 'Waterproof', value: '5 ATM' }]
  },
  {
    id: 'prod-fas-8',
    name: 'Classic Biker Genuine Leather Jacket Black',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 14999,
    originalPrice: 18999,
    rating: 4.8,
    reviewsCount: 110,
    image: 'https://images.unsplash.com/photo-1521223890158-f9f7c3d5d504?auto=format&fit=crop&w=800&q=80',
    stock: 10,
    salesCount: 290,
    description: '100% lambskin leather motorcycle jacket with YKK heavy duty zippers and satin lining.',
    features: ['100% Genuine Lambskin', 'YKK Metal Zippers', 'Quilted Shoulder Panels'],
    specs: [{ label: 'Style', value: 'Classic Biker Cut' }]
  },
  {
    id: 'prod-fas-9',
    name: 'Designer Polarized UV400 Aviator Sunglasses',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 3499,
    originalPrice: 4999,
    rating: 4.7,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
    stock: 30,
    salesCount: 820,
    description: 'TAC polarized anti-glare lenses with lightweight alloy metal frame and leather case.',
    features: ['UV400 Protection Lenses', 'Lightweight Metal Frame', 'Anti-Glare Polarized'],
    specs: [{ label: 'Lens Material', value: 'Triacetate Cellulose' }]
  },
  {
    id: 'prod-fas-10',
    name: 'Luxury Silk Pashmina Shawl Soft Warm Wrap',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 4499,
    originalPrice: 5999,
    rating: 4.9,
    reviewsCount: 175,
    image: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80',
    stock: 20,
    salesCount: 460,
    description: 'Traditional woven silk pashmina shawl with intricate paisley border motifs.',
    features: ['70% Silk 30% Pashmina Wool', 'Hand-knotted Fringe Trim', 'Reversible Dual Color Pattern'],
    specs: [{ label: 'Size', value: '200cm x 70cm' }]
  },

  // --- BEAUTY (6) ---
  {
    id: 'prod-bt-1',
    name: 'UmarMart Velvet Midnight Eau De Parfum 100ml',
    category: 'Beauty',
    categorySlug: 'beauty',
    price: 4999,
    originalPrice: 6499,
    rating: 5.0,
    reviewsCount: 289,
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
    isBestSeller: true,
    stock: 25,
    salesCount: 2100,
    badge: 'LUXURY ESSENCE',
    description: 'A captivating eau de parfum with Italian Bergamot, Sandalwood, Amber, and Tahitian Vanilla.',
    features: ['Extrait De Parfum Concentration', 'Artisanal Crystal Bottle', 'Unisex Scent'],
    specs: [{ label: 'Volume', value: '100ml' }]
  },
  {
    id: 'prod-bt-2',
    name: 'Advanced Hyaluronic Acid & Vitamin C Radiant Serum 50ml',
    category: 'Beauty',
    categorySlug: 'beauty',
    price: 2499,
    originalPrice: 3499,
    rating: 4.8,
    reviewsCount: 412,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
    isTrending: true,
    stock: 40,
    salesCount: 1850,
    description: 'Hydrating anti-aging serum with 2% pure hyaluronic acid, 15% Vitamin C, and Ferulic Acid.',
    features: ['Brightens Dark Spots', 'Intense 24H Hydration', 'Dermatologist Tested'],
    specs: [{ label: 'Volume', value: '50ml / 1.7 oz' }]
  },
  {
    id: 'prod-bt-3',
    name: 'Dyson Airwrap Multi-Styler Complete Long Nickel/Copper',
    category: 'Beauty',
    categorySlug: 'beauty',
    price: 185000,
    originalPrice: 199999,
    rating: 4.9,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
    stock: 5,
    salesCount: 95,
    description: 'Curl, shape, smooth and hide flyaways with no extreme heat using Coanda airflow technology.',
    features: ['Coanda Air Styling Tech', 'Intelligent Heat Control', 'Includes 6 Attachments'],
    specs: [{ label: 'Power', value: '1300 Watts' }]
  },
  {
    id: 'prod-bt-4',
    name: 'Matte Velvet Liquid Lipstick Gift Box Set 6 Pcs',
    category: 'Beauty',
    categorySlug: 'beauty',
    price: 2999,
    originalPrice: 3999,
    rating: 4.7,
    reviewsCount: 320,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
    stock: 35,
    salesCount: 1240,
    description: 'Long-wearing 16-hour transfer-proof matte liquid lipsticks enriched with Vitamin E and Jojoba Oil.',
    features: ['16-Hour Transfer Proof Formula', 'Non-Drying Matte Finish', '6 Nude & Red Shades'],
    specs: [{ label: 'Quantity', value: '6 Lipsticks x 5ml' }]
  },
  {
    id: 'prod-bt-5',
    name: 'Organic Moroccan Argan Hair Oil 100ml Pure Cold Pressed',
    category: 'Beauty',
    categorySlug: 'beauty',
    price: 1999,
    originalPrice: 2799,
    rating: 4.9,
    reviewsCount: 260,
    image: 'https://images.unsplash.com/photo-1608248597263-0057e43a4524?auto=format&fit=crop&w=800&q=80',
    stock: 50,
    salesCount: 2300,
    description: '100% pure organic Moroccan Argan oil for hair shine, heat protection, and deep conditioning.',
    features: ['100% Cold-Pressed Organic', 'Eliminates Frizz & Split Ends', 'Natural Heat Protectant'],
    specs: [{ label: 'Source', value: 'Morocco' }]
  },
  {
    id: 'prod-bt-6',
    name: 'Deep Cleansing Sonic Facial Brush & Massager',
    category: 'Beauty',
    categorySlug: 'beauty',
    price: 3499,
    originalPrice: 4999,
    rating: 4.6,
    reviewsCount: 180,
    image: 'https://images.unsplash.com/photo-1512290900676-26c2a4d4b51b?auto=format&fit=crop&w=800&q=80',
    stock: 28,
    salesCount: 610,
    description: 'Waterproof ultra-hygienic silicone facial cleansing device with T-Sonic pulsations.',
    features: ['8 Adjustable Sonic Speeds', 'IPX7 Waterproof', 'Ultra-Soft Medical Silicone'],
    specs: [{ label: 'Battery', value: 'USB Rechargeable' }]
  },

  // --- GROCERY (6) ---
  {
    id: 'prod-gro-1',
    name: 'Guard Supreme Super Kernel Basmati Rice 5kg Export Quality',
    category: 'Grocery',
    categorySlug: 'grocery',
    price: 2499,
    originalPrice: 2999,
    rating: 4.9,
    reviewsCount: 520,
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80',
    isBestSeller: true,
    stock: 60,
    salesCount: 3400,
    badge: 'EXPORT QUALITY',
    description: 'Aged extra long grain Super Kernel Basmati rice with aromatic fragrance and non-sticky cooking.',
    features: ['100% Aged Extra Long Grain', 'Naturally Aromatic Fragrance', 'Zero Broken Grains'],
    specs: [{ label: 'Weight', value: '5 kg' }]
  },
  {
    id: 'prod-gro-2',
    name: 'Tapal Danedar Tea Premium Blend 950g Pack',
    category: 'Grocery',
    categorySlug: 'grocery',
    price: 1499,
    originalPrice: 1699,
    rating: 4.9,
    reviewsCount: 890,
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?auto=format&fit=crop&w=800&q=80',
    stock: 80,
    salesCount: 5200,
    description: 'Pakistan’s favorite strong granular black tea blend for Karak Chai.',
    features: ['Granular Black Tea Leaves', 'Strong Rich Aroma', 'Ideal for Karak Chai'],
    specs: [{ label: 'Weight', value: '950g Eco-Pouch' }]
  },
  {
    id: 'prod-gro-3',
    name: 'Borges Extra Virgin Olive Oil 1 Litre Cold Extracted',
    category: 'Grocery',
    categorySlug: 'grocery',
    price: 3999,
    originalPrice: 4799,
    rating: 4.8,
    reviewsCount: 340,
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80',
    stock: 45,
    salesCount: 1980,
    description: '100% Spanish extra virgin olive oil cold extracted from finest Mediterranean olives.',
    features: ['Cold Extracted Spanish Olives', 'Rich in Heart-Healthy Omega 9', 'Ideal for Salads & Cooking'],
    specs: [{ label: 'Volume', value: '1 Litre Glass Bottle' }]
  },
  {
    id: 'prod-gro-4',
    name: 'Organic Raw Sidr Honey 500g Pure Wild Bee Honey',
    category: 'Grocery',
    categorySlug: 'grocery',
    price: 2999,
    originalPrice: 3800,
    rating: 5.0,
    reviewsCount: 210,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80',
    stock: 30,
    salesCount: 920,
    badge: '100% PURE ORGANIC',
    description: 'Unpasteurized raw wild Sidr honey harvested from Karak and Balochistan valleys.',
    features: ['100% Unfiltered Wild Sidr Honey', 'Rich Immune Booster', 'Lab Certified Pure'],
    specs: [{ label: 'Net Weight', value: '500g Jar' }]
  },
  {
    id: 'prod-gro-5',
    name: 'Illy Espresso Dark Roast Whole Coffee Beans 250g',
    category: 'Grocery',
    categorySlug: 'grocery',
    price: 2899,
    originalPrice: 3499,
    rating: 4.8,
    reviewsCount: 160,
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80',
    stock: 25,
    salesCount: 740,
    description: '100% Arabica dark roast coffee beans pressurized in tin canister for peak freshness.',
    features: ['100% Arabica Beans', 'Intense Cocoa & Caramel Notes', 'Made in Italy'],
    specs: [{ label: 'Weight', value: '250g Pressurized Can' }]
  },
  {
    id: 'prod-gro-6',
    name: 'Lindt Excellence 70% Cocoa Dark Chocolate Bar Pack of 3',
    category: 'Grocery',
    categorySlug: 'grocery',
    price: 1999,
    originalPrice: 2499,
    rating: 4.9,
    reviewsCount: 410,
    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80',
    stock: 50,
    salesCount: 2800,
    description: 'Smooth full-bodied dark chocolate crafted by Swiss master chocolatiers.',
    features: ['70% Pure Cocoa', 'Swiss Crafted Masterpiece', 'Includes 3x 100g Bars'],
    specs: [{ label: 'Pack Size', value: '3 x 100g' }]
  },

  // --- HOME APPLIANCES (8) ---
  {
    id: 'prod-ha-1',
    name: 'Smart Robotic Vacuum & Mop with Self-Empty Dock Station',
    category: 'Home Appliances',
    categorySlug: 'home-appliances',
    price: 34999,
    originalPrice: 44999,
    rating: 4.9,
    reviewsCount: 178,
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    isBestSeller: true,
    stock: 7,
    salesCount: 940,
    description: 'LiDAR 3D laser navigation robot vacuum with 6000Pa extreme suction and auto dust disposal.',
    features: ['6000Pa Ultra Suction Power', '60-Day Self-Emptying Dock', 'Sonic Scrubbing Mop'],
    specs: [{ label: 'Suction', value: '6000 Pa' }]
  },
  {
    id: 'prod-ha-2',
    name: 'Philips XXL Digital Touchscreen Air Fryer 7.2L 2000W',
    category: 'Home Appliances',
    categorySlug: 'home-appliances',
    price: 39999,
    originalPrice: 48999,
    rating: 4.9,
    reviewsCount: 450,
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    isFeatured: true,
    stock: 14,
    salesCount: 1650,
    badge: '90% LESS FAT',
    description: 'Rapid CombiAir technology air fryer for healthy oil-free cooking with digital preset menu.',
    features: ['90% Less Fat Rapid Air Tech', '7.2L Extra Large Family Capacity', '7 Digital Cooking Presets'],
    specs: [{ label: 'Power', value: '2000 Watts' }]
  },
  {
    id: 'prod-ha-3',
    name: 'DeLonghi Dedica Deluxe Espresso & Cappuccino Coffee Machine',
    category: 'Home Appliances',
    categorySlug: 'home-appliances',
    price: 54999,
    originalPrice: 62999,
    rating: 4.8,
    reviewsCount: 230,
    image: 'https://images.unsplash.com/photo-1517668808822-9ebe02f2a6e8?auto=format&fit=crop&w=800&q=80',
    stock: 9,
    salesCount: 580,
    description: '15-bar professional pump pressure espresso maker with adjustable milk frothing wand.',
    features: ['15-Bar Italian Pump Pressure', 'Thermoblock Heating System', 'Slim 6-Inch Stainless Steel Body'],
    specs: [{ label: 'Pressure', value: '15 Bar' }]
  },
  {
    id: 'prod-ha-4',
    name: 'Dawlance 1.5 Ton Inverter Split Air Conditioner Heat & Cool',
    category: 'Home Appliances',
    categorySlug: 'home-appliances',
    price: 165000,
    originalPrice: 185000,
    rating: 4.8,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
    stock: 12,
    salesCount: 890,
    badge: '75% ENERGY SAVER',
    description: 'T3 Tropicalized Inverter AC with Gold Fin protection and 75% electricity saving.',
    features: ['75% Energy Saving Inverter', 'T3 Tropical Heavy Duty Cooling', 'Gold Fin Anti-Rust Coating'],
    specs: [{ label: 'Capacity', value: '1.5 Ton (18000 BTU)' }]
  },
  {
    id: 'prod-ha-5',
    name: 'Tefal OptiGrill XL Intelligent Electric Indoor Grill',
    category: 'Home Appliances',
    categorySlug: 'home-appliances',
    price: 29999,
    originalPrice: 35999,
    rating: 4.7,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    stock: 16,
    salesCount: 370,
    description: 'Automatic thickness sensor grill with 9 automatic cooking programs for meat, chicken, and paninis.',
    features: ['Automatic Sensor Cooking', '9 Automatic Cooking Programs', 'Removable Dishwasher Safe Plates'],
    specs: [{ label: 'Power', value: '2000W' }]
  },
  {
    id: 'prod-ha-6',
    name: 'Panasonic 32L Convection Microwave Oven with Grill',
    category: 'Home Appliances',
    categorySlug: 'home-appliances',
    price: 32999,
    originalPrice: 38999,
    rating: 4.8,
    reviewsCount: 195,
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?auto=format&fit=crop&w=800&q=80',
    stock: 18,
    salesCount: 640,
    description: 'Inverter technology microwave oven for fast multi-stage cooking and baking.',
    features: ['Dual Cooking Convection + Grill', 'Inverter Precise Temperature Control', 'Stainless Steel Cavity'],
    specs: [{ label: 'Capacity', value: '32 Litres' }]
  },
  {
    id: 'prod-ha-7',
    name: 'Luminary AI Smart Home Hub & Security System',
    category: 'Home Appliances',
    categorySlug: 'home-appliances',
    price: 6999,
    originalPrice: 8999,
    rating: 4.8,
    reviewsCount: 142,
    image: 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
    stock: 18,
    salesCount: 780,
    description: 'Control your smart home with voice, 2K HD night vision cameras, and motion sensors.',
    features: ['Matter & Zigbee Support', 'AI Face & Motion Detection', '7-inch HD Touch Screen'],
    specs: [{ label: 'Connectivity', value: 'Wi-Fi 6' }]
  },
  {
    id: 'prod-ha-8',
    name: 'NutriBullet Pro 900W High Speed Blender & Extractor',
    category: 'Home Appliances',
    categorySlug: 'home-appliances',
    price: 12999,
    originalPrice: 15999,
    rating: 4.9,
    reviewsCount: 380,
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=800&q=80',
    stock: 25,
    salesCount: 1450,
    description: 'Nutrient extractor with 900W motor and stainless steel extractor blade.',
    features: ['900W High Torque Motor', 'Nutrient Extraction Blades', 'Includes 3 To-Go Cups'],
    specs: [{ label: 'Power', value: '900 Watts' }]
  },

  // --- SPORTS (6) ---
  {
    id: 'prod-sp-1',
    name: 'CA Sports Plus 15000 Player Edition English Willow Cricket Bat',
    category: 'Sports',
    categorySlug: 'sports',
    price: 44999,
    originalPrice: 52000,
    rating: 5.0,
    reviewsCount: 185,
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=80',
    isBestSeller: true,
    stock: 8,
    salesCount: 690,
    badge: 'PLAYER EDITION',
    description: 'Grade 1 English Willow professional cricket bat with massive sweet spot and 10+ straight grains.',
    features: ['Grade 1+ English Willow', 'Custom Toe Guard Fitted', 'Superb Balance & Pickup'],
    specs: [{ label: 'Grains', value: '10-12 Straight Grains' }]
  },
  {
    id: 'prod-sp-2',
    name: 'AeroGlide Ultra Lightweight Pro Carbon Running Shoes',
    category: 'Sports',
    categorySlug: 'sports',
    price: 8999,
    originalPrice: 11999,
    rating: 4.8,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    isTrending: true,
    stock: 20,
    salesCount: 1120,
    description: 'Marathon distance running sneakers with responsive nitrogen-infused foam and carbon plate.',
    features: ['Full Length Carbon Fiber Plate', 'Nitrogen-Infused Energy Foam', 'Breathable Engineered Mesh'],
    specs: [{ label: 'Weight', value: '195g' }]
  },
  {
    id: 'prod-sp-3',
    name: 'Adjustable Quick-Select Dumbbell Set 24kg Pair',
    category: 'Sports',
    categorySlug: 'sports',
    price: 32999,
    originalPrice: 39999,
    rating: 4.9,
    reviewsCount: 140,
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
    stock: 10,
    salesCount: 430,
    description: 'Replace 15 sets of weights with a single dial adjustment dumbbell from 2.5kg to 24kg.',
    features: ['Replaces 15 Dumbbell Sets', 'Dial Weight Selection System', 'Heavy Duty Molding'],
    specs: [{ label: 'Range', value: '2.5kg - 24kg per dumbbell' }]
  },
  {
    id: 'prod-sp-4',
    name: 'Yonex Astrox 99 Pro Graphite Badminton Racket Set',
    category: 'Sports',
    categorySlug: 'sports',
    price: 18999,
    originalPrice: 22500,
    rating: 4.8,
    reviewsCount: 160,
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=80',
    stock: 14,
    salesCount: 520,
    description: 'Head-heavy power smash badminton racquet with Namd graphite shaft technology.',
    features: ['Rotational Generator System', 'Namd Flex Graphite Shaft', 'Includes BG65 String & Cover'],
    specs: [{ label: 'Weight Class', value: '4U (83g)' }]
  },
  {
    id: 'prod-sp-5',
    name: 'Non-Slip Eco Friendly TPE Yoga Mat 6mm with Carrying Strap',
    category: 'Sports',
    categorySlug: 'sports',
    price: 2499,
    originalPrice: 3499,
    rating: 4.7,
    reviewsCount: 280,
    image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
    stock: 40,
    salesCount: 1850,
    description: 'High-density dual layer non-slip eco TPE yoga and fitness mat with alignment marks.',
    features: ['Body Alignment Lines Printed', 'Tear-Resistant Dual Layer TPE', 'Includes Free Cotton Strap'],
    specs: [{ label: 'Thickness', value: '6mm Cushioning' }]
  },
  {
    id: 'prod-sp-6',
    name: 'Garmin Forerunner 265 Running Smartwatch GPS',
    category: 'Sports',
    categorySlug: 'sports',
    price: 125000,
    originalPrice: 139000,
    rating: 4.9,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?auto=format&fit=crop&w=800&q=80',
    stock: 6,
    salesCount: 140,
    description: 'AMOLED touchscreen sports watch with training readiness score, HRV status, and 13-day battery.',
    features: ['Bright AMOLED Touchscreen', 'Advanced Training Readiness Score', 'Multi-Band GPS'],
    specs: [{ label: 'Battery', value: '13 Days in Smartwatch Mode' }]
  },

  // --- BOOKS (6) ---
  {
    id: 'prod-bk-1',
    name: 'Atomic Habits by James Clear (Hardcover Collector Edition)',
    category: 'Books',
    categorySlug: 'books',
    price: 1499,
    originalPrice: 1999,
    rating: 5.0,
    reviewsCount: 1240,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80',
    isBestSeller: true,
    stock: 100,
    salesCount: 6500,
    badge: '#1 BESTSELLER',
    description: 'An easy & proven way to build good habits and break bad ones. Over 15 million copies sold worldwide.',
    features: ['Hardcover Deluxe Collector Edition', 'Practical Step-by-Step Framework', 'Includes Goal Tracking Worksheets'],
    specs: [{ label: 'Pages', value: '320 Pages' }, { label: 'Language', value: 'English' }]
  },
  {
    id: 'prod-bk-2',
    name: 'The Psychology of Money by Morgan Housel (Paperback)',
    category: 'Books',
    categorySlug: 'books',
    price: 1299,
    originalPrice: 1699,
    rating: 4.9,
    reviewsCount: 890,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
    stock: 75,
    salesCount: 4200,
    description: 'Timeless lessons on wealth, greed, and happiness exploring how people think about money.',
    features: ['19 Short Stories on Wealth', 'Easy-to-Read Practical Lessons'],
    specs: [{ label: 'Pages', value: '256 Pages' }]
  },
  {
    id: 'prod-bk-3',
    name: 'Rich Dad Poor Dad by Robert Kiyosaki (25th Anniversary Edition)',
    category: 'Books',
    categorySlug: 'books',
    price: 1199,
    originalPrice: 1599,
    rating: 4.9,
    reviewsCount: 1560,
    image: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&w=800&q=80',
    stock: 90,
    salesCount: 7800,
    description: 'What the rich teach their kids about money that the poor and middle class do not!',
    features: ['Financial Literacy Classic', '25th Anniversary Special Insights'],
    specs: [{ label: 'Pages', value: '336 Pages' }]
  },
  {
    id: 'prod-bk-4',
    name: 'The Forty Rules of Love by Elif Shafak',
    category: 'Books',
    categorySlug: 'books',
    price: 1399,
    originalPrice: 1799,
    rating: 4.9,
    reviewsCount: 720,
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&w=800&q=80',
    stock: 60,
    salesCount: 3900,
    description: 'A novel of Rumi and Shams of Tabriz exploring love, spirituality and transformation.',
    features: ['International Bestselling Fiction', 'Inspiring Spiritual Themes'],
    specs: [{ label: 'Pages', value: '368 Pages' }]
  },
  {
    id: 'prod-bk-5',
    name: 'Deep Work: Rules for Focused Success in a Distracted World',
    category: 'Books',
    categorySlug: 'books',
    price: 1350,
    originalPrice: 1750,
    rating: 4.8,
    reviewsCount: 480,
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=800&q=80',
    stock: 45,
    salesCount: 2400,
    description: 'Cal Newport’s guide to mastering intense focus in an increasingly noisy world.',
    features: ['Strategies for Uninterrupted Focus', '4 Rules for Cultivating Deep Work'],
    specs: [{ label: 'Pages', value: '304 Pages' }]
  },
  {
    id: 'prod-bk-6',
    name: 'Sapiens: A Brief History of Humankind by Yuval Noah Harari',
    category: 'Books',
    categorySlug: 'books',
    price: 1599,
    originalPrice: 1999,
    rating: 4.9,
    reviewsCount: 930,
    image: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80',
    stock: 55,
    salesCount: 4800,
    description: 'Explore 70,000 years of human evolution, cognition, agriculture, and scientific revolutions.',
    features: ['Critically Acclaimed Global Phenomenon', 'Illustrated Maps & Timelines'],
    specs: [{ label: 'Pages', value: '464 Pages' }]
  }
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Hamza Malik',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    date: 'July 28, 2026',
    title: 'Mind-blowing iPhone PTA delivery speed & authentic product!',
    comment: 'Ordered the iPhone 15 Pro Max and was stunned by how quickly it arrived in Karachi. PTA official status verified instantly. Highly recommended!',
    verified: true,
    productName: 'Apple iPhone 15 Pro Max 256GB Titanium Blue (PTA Approved)',
    helpfulCount: 42,
    location: 'Karachi, Pakistan'
  },
  {
    id: 'rev-2',
    author: 'Ayesha Khan',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    date: 'July 24, 2026',
    title: 'The watch craftsmanship is breathtaking',
    comment: 'I bought the Royal Chronograph Automatic for my husband’s anniversary in Lahore. Paid safely via EasyPaisa and received doorstep delivery next day. Super impressed!',
    verified: true,
    productName: 'Royal Chronograph Automatic Sapphire Watch',
    helpfulCount: 29,
    location: 'Lahore, Pakistan'
  },
  {
    id: 'rev-3',
    author: 'Usman Tariq',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    date: 'July 19, 2026',
    title: 'Flash Sale discount was genuine & COD process was smooth',
    comment: 'Got the Samsung Galaxy S24 Ultra on flash sale. The camera zoom and live AI translation features are incredible. UmarMart is now my default store in Islamabad!',
    verified: true,
    productName: 'Samsung Galaxy S24 Ultra 512GB Titanium Gray (PTA Approved)',
    helpfulCount: 18,
    location: 'Islamabad, Pakistan'
  },
  {
    id: 'rev-4',
    author: 'Fatima Ahmed',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    date: 'July 15, 2026',
    title: 'Genuine English Willow Bat!',
    comment: 'The CA Player Edition cricket bat has 11 straight grains and phenomenal ping. Delivered safely right to my door in Rawalpindi.',
    verified: true,
    productName: 'CA Sports Plus 15000 Player Edition English Willow Cricket Bat',
    helpfulCount: 31,
    location: 'Rawalpindi, Pakistan'
  }
];

export const CURRENCIES: Currency[] = [
  { code: 'PKR', symbol: 'Rs. ', rate: 1.0 },
  { code: 'USD', symbol: '$', rate: 0.0036 },
  { code: 'AED', symbol: 'AED ', rate: 0.013 },
  { code: 'EUR', symbol: '€', rate: 0.0033 },
  { code: 'GBP', symbol: '£', rate: 0.0028 }
];

export const DEMO_USER = {
  id: 'usr-9821',
  name: 'Umar Shani',
  email: 'shaniumar87@gmail.com',
  isEmailVerified: true,
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  phone: '+92 315 2643791',
  addresses: [
    {
      id: 'addr-1',
      title: 'Home (Karachi)',
      isDefault: true,
      street: 'House 45, Block 4, Clifton',
      city: 'Karachi',
      country: 'Pakistan',
      zipCode: '75600',
      phone: '+92 315 2643791'
    },
    {
      id: 'addr-2',
      title: 'Office / Corporate (Lahore)',
      isDefault: false,
      street: 'Suite 302, Main Boulevard, Gulberg III',
      city: 'Lahore',
      country: 'Pakistan',
      zipCode: '54600',
      phone: '+92 300 8492019'
    }
  ],
  address: {
    street: 'House 45, Block 4, Clifton',
    city: 'Karachi',
    country: 'Pakistan',
    zipCode: '75600',
  },
  vipTier: 'Platinum VIP' as const,
  rewardPoints: 1250,
  joinedDate: 'January 2025',
  notificationsEnabled: true
};

export const MOCK_ORDERS = [
  {
    id: 'ord-88392',
    trackingNumber: 'UM-TRK-981240-PK',
    date: 'July 28, 2026',
    status: 'In Transit' as const,
    items: [
      {
        productId: 'prod-mob-1',
        name: 'Apple iPhone 15 Pro Max 256GB Titanium Blue (PTA Approved)',
        image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80',
        price: 485000,
        quantity: 1,
        selectedColor: 'Titanium Blue'
      }
    ],
    totalAmount: 485000,
    shippingAddress: 'House 45, Block 4, Clifton, Karachi, 75600, Pakistan',
    paymentMethod: 'EasyPaisa Mobile Wallet',
    estimatedDelivery: 'August 3, 2026'
  },
  {
    id: 'ord-77123',
    trackingNumber: 'UM-TRK-334102-PK',
    date: 'June 14, 2026',
    status: 'Delivered' as const,
    items: [
      {
        productId: 'prod-lap-8',
        name: 'CyberBlade RGB Mechanical Wireless Gaming Keyboard',
        image: 'https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=800&q=80',
        price: 5499,
        quantity: 1,
        selectedColor: 'Cyber Black'
      }
    ],
    totalAmount: 5499,
    shippingAddress: 'House 45, Block 4, Clifton, Karachi, 75600, Pakistan',
    paymentMethod: 'Cash on Delivery (COD)',
    estimatedDelivery: 'June 17, 2026'
  }
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'c-1',
    code: 'UMARVIP10',
    discountType: 'percentage',
    discountValue: 10,
    minSpend: 2000,
    expiryDate: '2026-12-31',
    usageLimit: 500,
    usedCount: 142,
    status: 'active',
  },
  {
    id: 'c-2',
    code: 'AZADISALE',
    discountType: 'fixed',
    discountValue: 1000,
    minSpend: 5000,
    expiryDate: '2026-08-31',
    usageLimit: 1000,
    usedCount: 389,
    status: 'active',
  },
  {
    id: 'c-3',
    code: 'WELCOME500',
    discountType: 'fixed',
    discountValue: 500,
    minSpend: 1500,
    expiryDate: '2026-11-15',
    usageLimit: 200,
    usedCount: 88,
    status: 'active',
  },
];

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    name: 'Umar Shani',
    email: 'shaniumar87@gmail.com',
    phone: '+92 315 2643791',
    city: 'Karachi',
    vipTier: 'Platinum VIP',
    totalOrders: 14,
    totalSpent: 125400,
    status: 'active',
    joinedDate: 'Jan 15, 2025',
  },
  {
    id: 'cust-2',
    name: 'Ali Raza',
    email: 'aliraza.pk@gmail.com',
    phone: '+92 300 8492019',
    city: 'Lahore',
    vipTier: 'Gold VIP',
    totalOrders: 6,
    totalSpent: 48900,
    status: 'active',
    joinedDate: 'Mar 22, 2025',
  },
  {
    id: 'cust-3',
    name: 'Fatima Zahra',
    email: 'fatima.design@outlook.com',
    phone: '+92 321 9845120',
    city: 'Islamabad',
    vipTier: 'Diamond VIP',
    totalOrders: 21,
    totalSpent: 289000,
    status: 'active',
    joinedDate: 'Nov 04, 2024',
  },
  {
    id: 'cust-4',
    name: 'Hamza Malik',
    email: 'hamza.malik99@yahoo.com',
    phone: '+92 333 1122334',
    city: 'Faisalabad',
    vipTier: 'Standard',
    totalOrders: 2,
    totalSpent: 12500,
    status: 'active',
    joinedDate: 'May 10, 2026',
  },
  {
    id: 'cust-5',
    name: 'Spam User',
    email: 'bot99@fakeaddress.com',
    phone: '+92 300 0000000',
    city: 'Rawalpindi',
    vipTier: 'Standard',
    totalOrders: 0,
    totalSpent: 0,
    status: 'blocked',
    joinedDate: 'Jul 01, 2026',
  },
];
